import React from 'react';
import Image from 'next/image';
import Head from 'next/head';
import { RxCross2 } from 'react-icons/rx';
import Link from 'next/link';

const SignLayout: React.FC<{ children: React.ReactElement }> = ({
  children,
}) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid min-h-screen place-content-center bg-gradient-to-tr from-sky-700 to-white py-20 text-black">
        <div className="relative flex min-h-[70vh] bg-white shadow-xl  shadow-sky-950">
          {children}
          <div className="h-full w-[25rem] max-md:hidden">
            <Image
              src="/signImage.jpg"
              className="h-full w-full object-cover"
              height={300}
              width={300}
              alt="Follow us on Twitter"
              loading="lazy"
            />
          </div>
          <Link href="/">
            <RxCross2
              className="absolute right-5 top-5 h-7 w-7 text-black"
              title="back to home"
            />
          </Link>
        </div>
      </div>
    </>
  );
};

export default SignLayout;
