import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { BiArrowBack } from 'react-icons/bi';
import { useAppSelector } from '@/store/hooks';
import { selectNotification } from '@/slice/notification.slice';
import Notification from '@/components/notification';
import Layout from '@/components/layout';
import UIButton from '@/components/common/button';

const SignLayout: React.FC<{ children: React.ReactElement }> = ({
  children,
}) => {
  const notification = useAppSelector(selectNotification);
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="relative flex min-h-screen items-center justify-center bg-white py-20 font-ysabeau text-black">
          {notification.notify && (
            <Notification
              message={notification.message}
              type={notification.type}
            />
          )}
          <div className="relative flex min-h-[70vh] w-full md:max-w-[60vw] xl:max-w-[40vw]">
            {children}
            <Link href="/">
              <UIButton className="absolute left-5 top-5 flex h-9 gap-2 px-5 text-black">
                <BiArrowBack />
                <span>Back</span>
              </UIButton>
            </Link>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default SignLayout;
